CRICKET_LEAGUE/CRICKET_LEAGUE/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from manager_users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('players/', include('manage_players.urls')),
    path('teams/', include('manage_teams.urls')),
    path('', include('manage_matches.urls')),
    path('fixtures/', include('fixtures_points.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', user_views.register, name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CRICKET_LEAGUE/manage_matches/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('matches/<int:pk>', views.MatchDetailView.as_view(),name='MatchDetail'),
    path('matches/list', views.MatchListView.as_view(),name='MatchList'), 
    path('pointlist', views.PointListView.as_view(),name='Pointlist'),  
    path('', views.home,name='HomePage'), 
]

CRICKET_LEAGUE/manage_teams/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('create', views.TeamCreateView.as_view(),name='TeamCreate'),
    path('update/<int:pk>', views.TeamUpdateView.as_view(),name='TeamUpdate'),
    path('<int:pk>', views.TeamDetailView.as_view(),name='TeamDetail'),
    path('delete/<int:pk>', views.TeamDeleteView.as_view(),name='TeamDelete'),
    path('list', views.TeamListView.as_view(),name='TeamList'), 
]

CRICKET_LEAGUE/manage_matches/models.py
from django.db import models
from fixtures_points.models import Fixture 
from manage_teams.models import Team 


class Point(models.Model):
    identifier = models.AutoField(primary_key=True)
    winner = models.ForeignKey(Team,on_delete=models.CASCADE,related_name='winner',blank=False,null=True)
    winner_point = models.IntegerField(default=3)
    loser_point = models.IntegerField(default=0)

    @classmethod
    def create(cls, team):
        point_obj = cls(winner=team)
        return point_obj


class Match(models.Model):
    identifier = models.AutoField(primary_key=True)
    fixture = models.OneToOneField(Fixture, on_delete=models.CASCADE,blank=True,null=True)
    point = models.OneToOneField(Point, on_delete=models.CASCADE,blank=True,null=True)

    @classmethod
    def create(cls, fixture,point):
        match_obj = cls(fixture=fixture,point=point)
        return match_obj



    

CRICKET_LEAGUE/manage_teams/models.py
from django.db import models


class Team(models.Model):
    identifier = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    logo_uri = models.ImageField(upload_to='media')
    state = models.CharField(max_length=20)

    def __str__(self):
        return self.name

CRICKET_LEAGUE/manage_matches/forms.py
from django import forms
from .models import Match,Point

class MatchDetailForm(forms.ModelForm):
    class Meta():
        model = Match
        fields= '__all__'


class PoimtDetailForm(forms.ModelForm):
    class Meta():
        model = Point
        fields= '__all__'

CRICKET_LEAGUE/manage_matches/views.py
from django.shortcuts import render,reverse,redirect
from django.urls import reverse_lazy
from .models import Match,Point
# from .forms import MatchDetailForm
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)
from django.db.models import Sum
from manage_matches.models import Team


class MatchListView(ListView):
    model = Match
    template_name = 'manage_matches/match_list.html'

class MatchDetailView(DetailView):
    model = Match
    template_name = 'manage_matches/match_detail.html'

###########################################################
#####################points################################
###########################################################

class PointListView(ListView):
    model = Team
    def get_queryset(self):
        query_set = Team.objects.values('name').order_by('name').annotate(points=Sum('winner__winner_point'))
        return query_set
        
    template_name = 'manage_matches/point_list.html'


def home(request):
    return redirect('MatchList')

CRICKET_LEAGUE/templates/manage_matches/match_detail.html
{% extends 'base.html' %}

{% block content %}
        <div class="card" style="width:100%; margin-bottom:15px;">
                        <div class="card-body">
                                <div class="card-title flex-set fixture-top">
                                        <div class="flex-set" style="margin-right:25px;">
                                                <div class="img-circle img-fixture">
                                                        <img src={{match.fixture.team1.logo_uri.url}} />
                                                </div>
                                                <div class="card" style="width:80%; margin-left:20px;border: 0px;">
                                                        <div class="card-body">
                                                                <div class="card-title flex-set fixture-top">
                                                                        <div class="flex-set" style="margin-left:10px;">
                                                                                <h2 style="margin-left:10px;font-weight:bold;">{{ match.fixture.team1.name }}</h2>                                                                                          
                                                                        </div>
                                                                </div>
                                                                <div class="card-button flex-set" style="justify-content: space-around;"> 
                                                                                {% if match.point.winner.identifier == match.fixture.team1.identifier %}
                                                                                        <button type="button" class="btn btn-success">Winner</button>
                                                                                        <h4 style="margin-left:10px;font-weight:normal;">{{ match.point.winner_point }} points  <i class="fa fa-arrow-up" aria-hidden="true"></i></h4>
                                                                                {% else %}
                                                                                        <button type="button" class="btn btn-danger">Loser</button>
                                                                                        <h4 style="margin-left:10px;font-weight:normal;">{{ match.point.loser_point }} point  <i class="fa fa-arrow-down" aria-hidden="true"></i> </h4>
                                                                                {% endif %}
                                                                </div>
                                                        </div>
                                                </div>
                                        </div> 
                                        <h4><i>VS</i></h4>
                                        <div class="flex-set" style="margin-left:25px;">
                                                <div class="img-circle img-fixture">
                                                        <img src={{match.fixture.team2.logo_uri.url}} />
                                                </div>                                                                                               
                                                <div class="card" style="width:80%; margin-left:20px;border: 0px;">
                                                        <div class="card-body">
                                                                <div class="card-title flex-set fixture-top">
                                                                        <div class="flex-set" style="margin-left:10px;">
                                                                                <h2 style="margin-left:10px;font-weight:bold;">{{ match.fixture.team2.name }}</h2>                                                                                          
                                                                        </div>
                                                                </div>
                                                                <div class="card-button flex-set" style="justify-content: space-around;"> 
                                                                                {% if match.point.winner.identifier == match.fixture.team2.identifier %}
                                                                                        <button type="button" class="btn btn-success">Winner</button>
                                                                                        <h4 style="margin-left:10px;font-weight:normal;">{{ match.point.winner_point }} points  <i class="fa fa-arrow-up" aria-hidden="true"></i></h4>
                                                                                {% else %}
                                                                                        <button type="button" class="btn btn-danger">Loser</button>
                                                                                        <h4 style="margin-left:10px;font-weight:normal;">{{ match.point.loser_point }} point  <i class="fa fa-arrow-down" aria-hidden="true"></i> </h4>
                                                                                {% endif %}
                                                                </div>
                                                        </div>
                                                </div>
                                        </div>
                                </div>
                                <div class="card-button flex-set" style="justify-content: center;"> 
                                        <h3 style="margin-left:10px;font-weight:bold;">Match date: {{ match.fixture.date }}</h3>
                                </div>
                        </div>
                </div>
{% endblock %}

CRICKET_LEAGUE/templates/manage_matches/match_list.html
{% extends 'base.html' %}

{% block content %}

        <div class="flex-set" style="margin-bottom:20px;">
                <h1 style="margin:0;padding:0;">Match List</h1>
        </div>

        {% for match in match_list %} 
                <div class="card" style="width:100%; margin-bottom:15px;">
                        <div class="card-body">
                                <div class="card-title flex-set fixture-top">
                                        <div class="flex-set" style="margin-right:25px;">
                                                <div class="img-circle img-fixture">
                                                        <img src={{match.fixture.team1.logo_uri.url}} />
                                                </div>
                                                <div class="card" style="width:80%; margin-left:20px;border: 0px;">
                                                        <div class="card-body">
                                                                <div class="card-title flex-set fixture-top">
                                                                        <div class="flex-set" style="margin-left:10px;">
                                                                                <h2 style="margin-left:10px;font-weight:bold;">{{ match.fixture.team1.name }}</h2>                                                                                          
                                                                        </div>
                                                                </div>
                                                                <div class="card-button flex-set" style="justify-content: space-around;"> 
                                                                                {% if match.point.winner.identifier == match.fixture.team1.identifier %}
                                                                                        <button type="button" class="btn btn-success">Winner</button>
                                                                                        <h4 style="margin-left:10px;font-weight:normal;">{{ match.point.winner_point }} points  <i class="fa fa-arrow-up" aria-hidden="true"></i></h4>
                                                                                {% else %}
                                                                                        <button type="button" class="btn btn-danger">Loser</button>
                                                                                        <h4 style="margin-left:10px;font-weight:normal;">{{ match.point.loser_point }} point  <i class="fa fa-arrow-down" aria-hidden="true"></i> </h4>
                                                                                {% endif %}
                                                                </div>
                                                        </div>
                                                </div>
                                        </div> 
                                        <h4><i>VS</i></h4>
                                        <div class="flex-set" style="margin-left:25px;">
                                                <div class="img-circle img-fixture">
                                                        <img src={{match.fixture.team2.logo_uri.url}} />
                                                </div>                                                                                               
                                                <div class="card" style="width:80%; margin-left:20px;border: 0px;">
                                                        <div class="card-body">
                                                                <div class="card-title flex-set fixture-top">
                                                                        <div class="flex-set" style="margin-left:10px;">
                                                                                <h2 style="margin-left:10px;font-weight:bold;">{{ match.fixture.team2.name }}</h2>                                                                                          
                                                                        </div>
                                                                </div>
                                                                <div class="card-button flex-set" style="justify-content: space-around;"> 
                                                                                {% if match.point.winner.identifier == match.fixture.team2.identifier %}
                                                                                        <button type="button" class="btn btn-success">Winner</button>
                                                                                        <h4 style="margin-left:10px;font-weight:normal;">{{ match.point.winner_point }} points  <i class="fa fa-arrow-up" aria-hidden="true"></i></h4>
                                                                                {% else %}
                                                                                        <button type="button" class="btn btn-danger">Loser</button>
                                                                                        <h4 style="margin-left:10px;font-weight:normal;">{{ match.point.loser_point }} point  <i class="fa fa-arrow-down" aria-hidden="true"></i> </h4>
                                                                                {% endif %}
                                                                </div>
                                                        </div>
                                                </div>
                                        </div>
                                </div>
                                <div class="card-button flex-set" style="justify-content: center;"> 
                                        <h3 style="margin-left:10px;font-weight:bold;">Match date: {{ match.fixture.date }}</h3>
                                </div>
                        </div>
                </div>
        {% endfor %}

{% endblock %}

CRICKET_LEAGUE/templates/manage_matches/point_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-striped table-hover">
        <thead>
                <tr>
                        <th>Team Name</th>
                        <th>Team Points</th>
                </tr>
        </thead>
        <tbody>
                {% for team in team_list %} 
                <tr>
                        <td scope="row">{{ team.name }}</td>
                        <td>
                        {% if team.points is None %}     
                        <h5 class="card-title">0</h5>
                   {% else %}
                        <h5 class="card-title">{{ team.points }}</h5>
                   {% endif %}
                        </td>
                </tr>
                {% endfor %}
        </tbody>
</table>
{% endblock %}